/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROG_H_RPCGEN
#define _PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROG 0x3012198
#define DATEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define BINDATE 1
extern  long * bindate_1(void *, CLIENT *);
extern  long * bindate_1_svc(void *, struct svc_req *);
#define UPTIME 2
extern  char ** uptime_1(void *, CLIENT *);
extern  char ** uptime_1_svc(void *, struct svc_req *);
#define AVAILABLE_MEMORY 3
extern  char ** available_memory_1(void *, CLIENT *);
extern  char ** available_memory_1_svc(void *, struct svc_req *);
#define CURRENT_USERS 4
extern  char ** current_users_1(void *, CLIENT *);
extern  char ** current_users_1_svc(void *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BINDATE 1
extern  long * bindate_1();
extern  long * bindate_1_svc();
#define UPTIME 2
extern  char ** uptime_1();
extern  char ** uptime_1_svc();
#define AVAILABLE_MEMORY 3
extern  char ** available_memory_1();
extern  char ** available_memory_1_svc();
#define CURRENT_USERS 4
extern  char ** current_users_1();
extern  char ** current_users_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROG_H_RPCGEN */
